baseURL: "https://slowpokelu.github.io/newmatrixvibes"
languageCode: "en-us"
title: "NewMatrixVibes"
theme: hugo-PaperMod 
#theme: smol-master
# defaultTheme: auto
defaultTheme: dark;

params:
    homeInfoParams:
        Title: Welcome To NewMatrixVibes.
        Content: "This website is a personal side-project and a platform to put out random stuff.
        \n\n
        カイゼン x HHKB x doom emacs x lofi x colemak-dh x rust
        \n\n
        "

    socialIcons:
        - name: "github"
          url: "https://github.com/slowpokelu/"
        - name: "twitter"
          url: "https://twitter.com/sl0wp0ke_LU"
        - name: "hackthebox"
          url: "https://www.hackthebox.eu/home/users/profile/163864"
        #- name: "email"
        #  url: ""


menu:
  main:
      - Name: "newtab"
        Pre: "<i class='fa fa-road'></i>"
        Weight: -100
        URL: "/pages/newtab/"
      - Name: "projects"
        Pre: "<i class='fa fa-road'></i>"
        Weight: -75
        URL: "/pages/project-collection/"
      - Name: "about"
        Pre: "<i class='fa fa-road'></i>"
        Weight: -50
        URL: "/pages/about-me/"

env: production

ignorefiles: [ "offlineORretiredOrReworked/", "notes/"]

publishDir: "docs"